[package]
name = "chromium-password-stealer"
version = "0.1.0"
edition = "2021"

[dependencies]
windows-sys = { version = "0.59.0", features = ["Win32_Foundation", "Win32_Security_Cryptography", "Win32_System_Memory"] }
serde_json = "1.0.128"
base64 = "0.22.1"
hex = "0.4.3"
